
categorical_features: ['person_home_ownership', 'loan_grade', 'loan_intent', 'cb_person_default_on_file']
continuous_feature: person_age
hue_feature: loan_status



hist_columns:
  - person_age
  - person_income
  - loan_amnt
  - loan_int_rate
  - person_emp_length
  - cb_person_cred_hist_length

hue_column: loan_status

cat_cols: ['person_home_ownership', 'loan_intent', 'loan_grade']
stand_col: ['person_age', 'person_income','person_emp_length', 'loan_amnt','loan_int_rate', 'loan_percent_income','cb_person_cred_hist_length']






models_params:
  LogisticRegression:
    C: 1.0
    solver: liblinear
    max_iter: 100
  XGBoost:
    n_estimators: 100
    learning_rate: 0.1
    use_label_encoder: false
    verbosity: 1
  LinearSVC:
    C: 1.0
    kernel: linear
    probability: true
  KNeighborsClassifier:
    n_neighbors: 5

# ==================== MODEL SELECTION ====================
selection_metric: "roc_auc"  # Options: "roc_auc" or "accuracy"
cv_folds: 10

# ==================== LOGISTIC REGRESSION PARAMETERS ====================
lr_params:
  max_iter: 1000
  solver: 'lbfgs'
  penalty: 'l2'
  C: 1.0
  random_state: 42
  n_jobs: -1
  class_weight: 'balanced'  # or null for no balancing

# ==================== RANDOM FOREST PARAMETERS ====================
rf_params:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 10
  min_samples_leaf: 4
  max_features: 'sqrt'
  random_state: 42
  n_jobs: -1
  class_weight: 'balanced'
  bootstrap: true
  oob_score: true

# ==================== XGBOOST PARAMETERS ====================
xgb_params:
  # Core parameters
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  
  # Regularization
  reg_alpha: 0.0
  reg_lambda: 1.0
  gamma: 0.0
  min_child_weight: 1
  
  # Other
  random_state: 42
  tree_method: 'auto'
  objective: 'binary:logistic'
  scale_pos_weight: 1  # For imbalanced datasets
  
  # Evaluation (handled separately in fit)
  eval_metric: 'auc'
  early_stopping_rounds: 10  # Optional


loan_economics:
  loan_term_years: 3.0
  interest_rate: 0.085
  operating_cost_rate: 0.025
  cost_of_capital: 0.04
  default_loss_rate: 0.65
  avg_time_to_default: 0.5